### ISSUE TITLE
assignment5 피보나치 수열, 이진탐색

### ISSUE THREAD

**Issue by fmowl10** [fmowl10/kmucs_swp2_class_2_Team_5#1]
이 아래에 댓글을 달아주세요.

**Comment by jiyeoun** [comment]
제 코드는 피드백 받은 전 후로 나눠서 다 올렸습니다. 
기다려도 나머지 분들 코드가 올라오지 않아서 일단 진석님 코드만 리뷰할게요.
솔직히 진석님의 전체적인 코드는 제 눈으로 봤을때는 딱히 더 좋은 방향으로 피드백을 드릴만한 부분이 보이지 않습니다. 
그래도 억지로 한가지 뽑자면 피보나치 수열 코드에서 변수 이름을 간단하게 설정한거 정도..? 밖에 없겠네요.
사실 이것도 코드가 간단해서 굳이 변수이름에 의미를 둘 필요는 없다고 생각하지만ㅎㅎ
